export interface EngineeringCapability {
  id: string;
  slug: string;
  title: string;
  tagline: string;
  hero: string;
  introduction: string;
  cardDescription: string;
  cardPills: string[];
  image: string;
  bgImage?: string;
  leftButtonText?: string;
  rightButtonText?: string;
  rightVisualTitle?: string;
  rightVisualSubtitle?: string;
  rightVisualImage?: string;
  sidebarTheme?: 'light' | 'dark';
  sidebarDescription?: string;
  sidebarButton1Text?: string;
  sidebarButton2Text?: string;
  sidebarBadges?: string[];
  iconName: 'Factory' | 'Cog' | 'Cpu' | 'BrainCircuit' | 'Building2' | 'FileText' | 'Briefcase' | 'BarChart';
  sections: string[];
  deliverables?: string[];
  software?: string[];
  industries?: string[];
}

export const engineeringCapabilities: EngineeringCapability[] = [
  {
    id: 'plant-process-engineering',
    slug: 'plant-process-engineering',
    title: 'Plant & Process Engineering',
    tagline: 'PROCESS & CLEANER TOMORROW',
    hero: 'Engineering complete process facilities from concept to commissioning.',
    introduction:
      'GTS delivers multidisciplinary plant and process engineering for oil & gas, LNG, petrochemical, chemical, hydrogen, renewable fuels, pharmaceuticals, food processing, and industrial manufacturing facilities.',
    cardDescription:
      'End-to-end engineering for process plants, refineries, LNG, chemicals, and industrial facilities.',
    cardPills: ['FEED', 'Process Design', 'Piping', 'Pipeline', 'Offshore', 'EPC Support'],
    image: '/image/our enginerring soluutions/Plant & Process Engineering.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/plant-and-process-enginerring-bg.jpg',
    leftButtonText: '← CONCEPT TO COMMISSIONING',
    rightButtonText: 'PROCESS & CLEANER TOMORROW →',
    rightVisualTitle: 'From Concept to Commissioning',
    rightVisualSubtitle: 'Turning ideas into high-performing assets',
    rightVisualImage: '/image/our enginerring soluutions/Plant & Process Engineering.jpg',
    sidebarTheme: 'light',
    sidebarDescription: 'Collaborate with our engineering experts to turn your process vision into a safe, efficient, and sustainable reality.',
    sidebarButton1Text: 'Request Engineering Support',
    sidebarButton2Text: 'Contact GTS',
    sidebarBadges: ['Sustainability', 'Safety', 'Operational Excellence'],
    iconName: 'Factory',
    sections: [
      'Process Design',
      'FEED Engineering',
      'Detailed Engineering',
      'Plant Layout',
      'Piping Engineering',
      'Equipment Engineering',
      'Utility Systems',
      'Process Simulation',
      'EPC Support',
      'Commissioning Support',
    ],
    deliverables: [
      'PFDs',
      'P&IDs',
      'Heat & Mass Balance',
      'Equipment Datasheets',
      'Line Lists',
      'Hydraulic Calculations',
      'Material Requisitions',
    ],
    industries: [
      'Oil & Gas',
      'LNG',
      'Chemical',
      'Distillery',
      'Power',
      'Hydrogen',
      'Water',
    ],
  },
  {
    id: 'product-engineering',
    slug: 'product-engineering',
    title: 'Product Engineering',
    tagline: 'IDEAS TO IMPACT',
    hero: 'Engineering Better Products from Concept to Production',
    introduction:
      'GTS provides comprehensive mechanical product development, from concept generation and CAD modeling through reverse engineering, design optimization, and prototype validation.',
    cardDescription:
      'Mechanical product development from concept to manufacturing through CAD, reverse engineering and prototyping.',
    cardPills: ['Mechanical Design', 'CAD', 'CAE', 'Reverse Engineering', 'DFM', 'Prototyping'],
    image: '/image/our enginerring soluutions/Product Engineering.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/product enginerring bg.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'IDEAS TO IMPACT →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'IDEAS TO IMPACT',
    rightVisualImage: '/image/our enginerring soluutions/Product Engineering.jpg',
    sidebarTheme: 'light',
    sidebarDescription: 'Collaborate with our engineering experts to turn your product vision into a safe, efficient, and manufacturable reality.',
    sidebarButton1Text: 'Request Engineering Support',
    sidebarButton2Text: 'Contact GTS',
    sidebarBadges: ['Innovation', 'Quality', 'Speed to Market'],
    iconName: 'Cog',
    sections: [
      'Mechanical Design',
      'Product Development',
      'Reverse Engineering',
      'CAD Modelling',
      'Design Optimization',
      'DFM',
      'GD&T',
      'Prototype Development',
    ],
    deliverables: [
      '3D CAD Models',
      'Manufacturing Drawings',
      'BOM',
      'Assembly Drawings',
      'Design Validation',
      'Prototype Support',
    ],
    industries: [
      'Heavy Engineering',
      'Industrial Machinery',
      'Rail & Transportation',
      'Automotive',
      'Aerospace',
      'Manufacturing',
      'Consumer Products',
    ],
  },
  {
    id: 'simulation-digital-validation',
    slug: 'simulation-digital-validation',
    title: 'Simulation & Digital Validation',
    tagline: 'VIRTUAL ENGINEERING REAL RESULTS',
    hero: 'Virtual Engineering Before Physical Manufacturing',
    introduction:
      'High-fidelity engineering simulation, multi-physics analysis, and digital validation to optimize design performance, enhance reliability, and accelerate physical testing cycles.',
    cardDescription:
      'Advanced CAE, CFD, FEA and digital validation to optimize performance, reliability, and safety.',
    cardPills: ['FEA', 'CFD', 'Thermal Analysis', 'Structural Analysis', 'Optimization', 'Fatigue'],
    image: '/image/our enginerring soluutions/Simulation & Digital Validation.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/simulation and digital bg.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'VIRTUAL ENGINEERING REAL RESULTS →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'VIRTUAL ENGINEERING REAL RESULTS',
    rightVisualImage: '/image/our enginerring soluutions/Simulation & Digital Validation.jpg',
    sidebarTheme: 'dark',
    sidebarDescription: 'Consult with our engineering directors, request work package estimates, or scale dedicated project teams.',
    sidebarButton1Text: 'Submit Engineering Request',
    sidebarButton2Text: 'Consult info@gtsusainc.com',
    iconName: 'Cpu',
    sections: [
      'Mechanical Design',
      'CFD',
      'Thermal Analysis',
      'Fatigue Analysis',
      'Structural Analysis',
      'Vibration Studies',
      'Design Optimization',
      'Digital Validation',
    ],
    software: [
      'ANSYS',
      'ABAQUS',
      'LS-DYNA',
      'Altair HyperWorks',
      'SIEMENS Simcenter',
      'OpenFOAM',
      'MATLAB',
    ],
    deliverables: [
      'Simulation Reports',
      'Fatigue Life Assessment',
      'Optimization Recommendations',
      'Design Validation',
      'Thermal Performance',
      'Digital Twin Models',
      'Load & Stress Analysis',
      'Vibration & Dynamics Response',
      'Compliance Documentation',
    ],
    industries: [
      'Heavy Engineering',
      'Industrial Machinery',
      'Rail & Transportation',
      'Automotive',
      'Aerospace',
      'Manufacturing',
      'Consumer Products',
    ],
  },
  {
    id: 'automation-ai-industry-4',
    slug: 'automation-ai-industry-4',
    title: 'Automation, AI & Industry 4.0',
    tagline: 'AUTOMATION INTELLIGENCE HIGHER PERFORMANCE',
    hero: 'Connecting Intelligent Factories with Smart Automation',
    introduction:
      'End-to-end industrial automation, DCS/SCADA programming, AI-driven operations, and IIoT architectures to build smart, connected, and autonomous industrial facilities.',
    cardDescription:
      'Industrial automation, control systems and AI-driven solutions for intelligent operations.',
    cardPills: ['SCADA', 'PLC', 'Digital Twins', 'Industrial IoT', 'AI Analytics', 'Predictive Maintenance'],
    image: '/image/our enginerring soluutions/Automation, AI & Industry 4.0.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/automotives and ai industry bg.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'AUTOMATION INTELLIGENCE HIGHER PERFORMANCE →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'AUTOMATION INTELLIGENCE HIGHER PERFORMANCE',
    rightVisualImage: '/image/our enginerring soluutions/Automation, AI & Industry 4.0.jpg',
    sidebarTheme: 'dark',
    sidebarDescription: 'Consult with our engineering directors, request work package estimates, or scale dedicated project teams.',
    sidebarButton1Text: 'Submit Engineering Request',
    sidebarButton2Text: 'Consult info@gtsusainc.com',
    sidebarBadges: ['Innovation', 'Safety', 'Sustainability', 'Operational Excellence'],
    iconName: 'BrainCircuit',
    sections: [
      'PLC Programming',
      'SCADA',
      'DCS',
      'HMI',
      'Industrial IoT',
      'AI Analytics',
      'Predictive Maintenance',
      'Digital Twins',
    ],
    software: [
      'SIEMENS TIA Portal',
      'Rockwell Automation',
      'AVEVA',
      'Schneider Electric',
      'MATLAB',
      'python',
      'Ignition!',
    ],
    deliverables: [
      'Control Philosophy',
      'PLC Programs',
      'Loop Diagrams & I/O Lists',
      'SCADA Screens',
      'FAT/SAT',
      'Network Architecture',
      'Instrument Index',
      'Functional Design Specifications',
      'Commissioning Support',
    ],
    industries: [
      'Oil & Gas',
      'LNG',
      'Chemical',
      'Petrochemical',
      'Power Generation',
      'Hydrogen',
      'Water & Wastewater',
      'Pharmaceuticals',
      'Food & Beverage',
      'Manufacturing',
    ],
  },
  {
    id: 'steel-detailing-structural-engineering',
    slug: 'steel-detailing-structural-engineering',
    title: 'Steel Detailing & Structural Engineering',
    tagline: 'STRONGER INFRASTRUCTURE FOR A BRIGHTER TOMORROW',
    hero: 'Structural Engineering for Industrial Infrastructure',
    introduction:
      'Precision structural steel detailing, Tekla 3D modeling, connection design, and fabrication drawings for heavy industrial facilities, pipe racks, platforms, and infrastructure assets.',
    cardDescription:
      'High-accuracy structural design, steel detailing and fabrication support for industrial and infrastructure projects.',
    cardPills: ['Structural Design', 'Tekla Modeling', 'Shop Drawings', 'Pipe Racks', 'Platforms'],
    image: '/image/our enginerring soluutions/Steel Detailing & Structural Engineering.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/steal and detailing bg.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'STRONGER INFRASTRUCTURE FOR A BRIGHTER TOMORROW →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'STRONGER INFRASTRUCTURE FOR A BRIGHTER TOMORROW',
    rightVisualImage: '/image/our enginerring soluutions/Steel Detailing & Structural Engineering.jpg',
    sidebarTheme: 'dark',
    sidebarDescription: 'Consult with our engineering directors, request work package estimates, or scale dedicated project teams.',
    sidebarButton1Text: 'Submit Engineering Request',
    sidebarButton2Text: 'Consult info@gtsusainc.com',
    sidebarBadges: ['Innovation', 'Safety', 'Sustainability', 'Operational Excellence'],
    iconName: 'Building2',
    sections: [
      'Structural Design',
      'Steel Detailing',
      'Tekla Modeling',
      'Pipe Rack Design',
      'Connection Design',
      'Pipe Supports',
      'Platforms & Structures',
      'Fabrication Drawings',
      'Shop Drawings',
      'Erection Engineering',
    ],
    software: [
      'Tekla',
      'AUTODESK AutoCAD',
      'AUTODESK Revit',
      'STAAD.Pro',
      'RAM Structural System',
      'IDEA StatiCa',
      '3D SolidWorks',
    ],
    deliverables: [
      'Tekla 3D Models',
      'Fabrication Drawings',
      'Connection Design Calculations',
      'Shop Detail Drawings',
      'Erection Diagrams',
      'General Arrangement Drawings (GA)',
      'Anchor Bolt Plans',
      'Advanced Bill of Materials (ABM)',
      'Material Take-offs (MTO)',
    ],
    industries: [
      'Oil & Gas',
      'LNG',
      'Chemical',
      'Petrochemical',
      'Power Generation',
      'Water & Wastewater',
      'Mining & Metals',
      'Manufacturing',
      'Infrastructure',
      'Marine & Offshore',
    ],
  },
  {
    id: 'technical-documentation-asset-intelligence',
    slug: 'technical-documentation-asset-intelligence',
    title: 'Technical Documentation & Asset Intelligence',
    tagline: 'ENGINEERING INFORMATION FOR LONGER ASSET LIFE',
    hero: 'Engineering Information that Supports the Entire Asset Lifecycle',
    introduction:
      'Comprehensive engineering data management, PLM administration, interactive O&M manuals, and intelligent asset documentation to support compliance, maintenance, and lifecycle operations.',
    cardDescription:
      'Structured engineering content, PLM support and asset documentation for the complete asset lifecycle.',
    cardPills: ['PLM', 'Engineering Data Management', 'Asset Documentation', 'Intelligent Documentation'],
    image: '/image/our enginerring soluutions/Technical Documentation & Aset Intelligence.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/tec hnical documentation bg.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'ENGINEERING INFORMATION FOR LONGER ASSET LIFE →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'ENGINEERING INFORMATION FOR LONGER ASSET LIFE',
    rightVisualImage: '/image/our enginerring soluutions/Technical Documentation & Aset Intelligence.jpg',
    sidebarTheme: 'dark',
    sidebarDescription: 'Consult with our engineering directors, request work package estimates, or scale dedicated project teams.',
    sidebarButton1Text: 'Submit Engineering Request',
    sidebarButton2Text: 'Consult info@gtsusainc.com',
    sidebarBadges: ['Innovation', 'Safety', 'Sustainability', 'Operational Excellence'],
    iconName: 'FileText',
    sections: [
      'PLM',
      'Engineering Data Management',
      'Technical Manuals',
      'O&M Manuals',
      'Asset Documentation',
      'Intelligent Documentation',
      'Document Control',
      'Digital Records',
    ],
    software: [
      'Teamcenter',
      'AVEVA',
      'SAP',
      'IBM Maximo',
      'AUTODESK Vault',
      '3DEXPERIENCE',
      'OpenBOM',
    ],
    deliverables: [
      'Interactive O&M Manuals',
      'PLM Data Schemas',
      'Engineering Data Standards',
      'As-Built Documentation',
      'Compliance Records',
      'Document Control Procedures',
      'Digital Parts Catalogs',
      'Asset Information Models',
      'Digital Twin Documentation',
    ],
    industries: [
      'Oil & Gas',
      'LNG',
      'Chemical',
      'Petrochemical',
      'Power Generation',
      'Water & Wastewater',
      'Mining & Metals',
      'Manufacturing',
      'Infrastructure',
      'Marine & Offshore',
    ],
  },
  {
    id: 'project-engineering-advisory',
    slug: 'project-engineering-advisory',
    title: 'Project Engineering & Advisory',
    tagline: 'EXPERTISE THAT DELIVERS',
    hero: 'Managing Engineering Projects from Planning through Delivery',
    introduction:
      'Integrated project management, schedule control, cost engineering, owner’s engineering advisory, and commissioning oversight to deliver complex capital projects on time and within budget.',
    cardDescription:
      'Engineering advisory, project controls, commissioning support and lifecycle consulting.',
    cardPills: ['Project Controls', 'Cost Engineering', 'Commissioning Support', "Owner's Engineer"],
    image: '/image/our enginerring soluutions/Project Engineering & Advisory.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/project enginerring and advisory.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'EXPERTISE THAT DELIVERS →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'EXPERTISE THAT DELIVERS',
    rightVisualImage: '/image/our enginerring soluutions/Project Engineering & Advisory.jpg',
    sidebarTheme: 'dark',
    sidebarDescription: 'Consult with our engineering directors, request work package estimates, or scale dedicated project teams.',
    sidebarButton1Text: 'Submit Engineering Request',
    sidebarButton2Text: 'Consult info@gtsusainc.com',
    sidebarBadges: ['Innovation', 'Safety', 'Sustainability', 'Operational Excellence'],
    iconName: 'Briefcase',
    sections: [
      'Project Management',
      'Project Controls',
      'Cost Engineering',
      'Schedule Management',
      'Risk Management',
      "Owner's Engineer",
      'Commissioning',
      'Construction Support',
    ],
    software: [
      'P6 Primavera',
      'SAP',
      'Bentley',
      'AVEVA',
      'AUTODESK Construction Cloud',
      'Microsoft Project',
      'Power BI',
    ],
    deliverables: [
      'Project Execution Plans (PEP)',
      'Cost Estimates & WBS',
      'Project Controls Reports',
      'Integrated Master Schedules (Primavera/MS Project)',
      'Risk Registers',
      'Schedule Recovery Plans',
      'Commissioning Checklists',
      'Construction Handover Packages',
      "Owner's Engineering Reports",
    ],
    industries: [
      'Oil & Gas',
      'LNG',
      'Chemical',
      'Petrochemical',
      'Power Generation',
      'Water & Wastewater',
      'Mining & Metals',
      'Manufacturing',
      'Infrastructure',
      'Marine & Offshore',
    ],
  },
  {
    id: 'digital-engineering-asset-lifecycle',
    slug: 'digital-engineering-asset-lifecycle',
    title: 'Digital Engineering & Asset Lifecycle',
    tagline: 'DIGITAL TODAY SUSTAINABLE TOMORROW',
    hero: 'Digital Transformation Across the Complete Asset Lifecycle',
    introduction:
      'Digital twin integration, asset performance management, spatial GIS analytics, predictive AI, and sustainability metrics to optimize industrial assets throughout their complete lifecycle.',
    cardDescription:
      'Digital twins, engineering analytics and lifecycle solutions to maximize asset performance and sustainability.',
    cardPills: ['Digital Twin', 'Data Analytics', 'GIS', 'AI Enabled Engineering', 'Sustainability'],
    image: '/image/our enginerring soluutions/Digital Engineering & Asset Life Cycle.jpg',
    bgImage: '/image/our enginerring soluutions/our enginerring capabilities bg image/digital enginerring and assest lifecycle.jpg',
    leftButtonText: '← BACK TO CAPABILITIES',
    rightButtonText: 'DIGITAL TODAY SUSTAINABLE TOMORROW →',
    rightVisualTitle: 'ENGINEERING FOCUS',
    rightVisualSubtitle: 'DIGITAL TODAY SUSTAINABLE TOMORROW',
    rightVisualImage: '/image/our enginerring soluutions/Digital Engineering & Asset Life Cycle.jpg',
    iconName: 'BarChart',
    sections: [
      'Digital Twin Development',
      'Asset Performance Management',
      'GIS Spatial Analytics',
      'Engineering Data Analytics',
      'AI Predictive Maintenance',
      'Reality Capture & Laser Scanning',
      'Sustainability Metrics',
      'Lifecycle Optimization',
    ],
    software: [
      'Azure Digital Twins',
      'AVEVA PI',
      'Bentley AssetWise',
      'Power BI',
      'Python',
      'AWS IoT TwinMaker',
    ],
    deliverables: [
      'Digital Twin Architectures',
      'Asset Health Dashboards',
      'GIS Spatial Models',
      'Predictive Failure Models',
      'Carbon & Energy Footprint Reports',
      'Lifecycle Cost Models',
    ],
    industries: [
      'Oil & Gas',
      'Power & Utilities',
      'Manufacturing',
      'Infrastructure',
      'Chemicals',
      'Smart Cities',
    ],
  },
];

export { engineeringCapabilities as solutionCapabilities };
